// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdfservice} from '../models';

export function AddTextWatermark(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function CompressPDF(arg1:string,arg2:string):Promise<void>;

export function DecryptPDF(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportPDF(arg1:Array<pdfservice.PageSpec>,arg2:string):Promise<void>;

export function FinalizeFlatten(arg1:string,arg2:string):Promise<void>;

export function FlattenDocument(arg1:Array<string>,arg2:string):Promise<void>;

export function ImagesToPDF(arg1:Array<string>,arg2:string):Promise<void>;

export function InitFlattenSession():Promise<string>;

export function ListAttachments(arg1:string):Promise<Array<string>>;

export function ProtectPDF(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean):Promise<void>;

export function ReadPDFFile(arg1:string):Promise<Array<number>>;

export function RemoveAnnotations(arg1:string,arg2:string):Promise<void>;

export function RemoveAttachments(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RemoveMetadata(arg1:string,arg2:string):Promise<void>;

export function SaveTempFile(arg1:string,arg2:string):Promise<string>;

export function SelectAndReadPDF():Promise<Record<string, any>>;

export function SelectMultipleImages():Promise<Array<string>>;

export function SelectSavePath(arg1:string):Promise<string>;

export function WriteFlattenPage(arg1:string,arg2:number,arg3:string):Promise<void>;
