// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportPDF(arg1:Array<main.PageSpec>,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ReadPDFFile(arg1:string):Promise<Array<number>>;

export function SelectAndReadPDF():Promise<Record<string, any>>;

export function SelectSavePath(arg1:string):Promise<string>;
