// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTextWatermark(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddTextWatermark'](arg1, arg2, arg3, arg4, arg5);
}

export function CompressPDF(arg1, arg2) {
  return window['go']['main']['App']['CompressPDF'](arg1, arg2);
}

export function DecryptPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptPDF'](arg1, arg2, arg3);
}

export function ExportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImagesToPDF(arg1, arg2) {
  return window['go']['main']['App']['ImagesToPDF'](arg1, arg2);
}

export function ProtectPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProtectPDF'](arg1, arg2, arg3, arg4);
}

export function ReadPDFFile(arg1) {
  return window['go']['main']['App']['ReadPDFFile'](arg1);
}

export function SaveBase64ToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveBase64ToFile'](arg1, arg2);
}

export function SelectAndReadPDF() {
  return window['go']['main']['App']['SelectAndReadPDF']();
}

export function SelectMultipleImages() {
  return window['go']['main']['App']['SelectMultipleImages']();
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}
