// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTextWatermark(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function CompressPDF(arg1:string,arg2:string):Promise<void>;

export function DecryptPDF(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportPDF(arg1:Array<main.PageSpec>,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ImagesToPDF(arg1:Array<string>,arg2:string):Promise<void>;

export function ProtectPDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ReadPDFFile(arg1:string):Promise<Array<number>>;

export function SaveBase64ToFile(arg1:string,arg2:string):Promise<void>;

export function SelectAndReadPDF():Promise<Record<string, any>>;

export function SelectMultipleImages():Promise<Array<string>>;

export function SelectSavePath(arg1:string):Promise<string>;
