// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTextWatermark(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddTextWatermark'](arg1, arg2, arg3, arg4, arg5);
}

export function CompressPDF(arg1, arg2) {
  return window['go']['main']['App']['CompressPDF'](arg1, arg2);
}

export function DecryptPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptPDF'](arg1, arg2, arg3);
}

export function ExportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2);
}

export function FinalizeFlatten(arg1, arg2) {
  return window['go']['main']['App']['FinalizeFlatten'](arg1, arg2);
}

export function FlattenDocument(arg1, arg2) {
  return window['go']['main']['App']['FlattenDocument'](arg1, arg2);
}

export function ImagesToPDF(arg1, arg2) {
  return window['go']['main']['App']['ImagesToPDF'](arg1, arg2);
}

export function InitFlattenSession() {
  return window['go']['main']['App']['InitFlattenSession']();
}

export function ListAttachments(arg1) {
  return window['go']['main']['App']['ListAttachments'](arg1);
}

export function ProtectPDF(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ProtectPDF'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ReadPDFFile(arg1) {
  return window['go']['main']['App']['ReadPDFFile'](arg1);
}

export function RemoveAnnotations(arg1, arg2) {
  return window['go']['main']['App']['RemoveAnnotations'](arg1, arg2);
}

export function RemoveAttachments(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveAttachments'](arg1, arg2, arg3);
}

export function RemoveMetadata(arg1, arg2) {
  return window['go']['main']['App']['RemoveMetadata'](arg1, arg2);
}

export function SaveImagePage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveImagePage'](arg1, arg2, arg3);
}

export function SaveTempFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTempFile'](arg1, arg2);
}

export function SelectAndReadPDF() {
  return window['go']['main']['App']['SelectAndReadPDF']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectMultipleImages() {
  return window['go']['main']['App']['SelectMultipleImages']();
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}

export function WriteFlattenPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteFlattenPage'](arg1, arg2, arg3);
}
